### PR TITLE
Create metadata and key files in mode 0600 (owner-only read/write)

### PR DESCRIPTION
**Pull request by dolph**
Fixes issue 157 in Google Code:

  https://code.google.com/p/keyczar/issues/detail?id=157&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Implementation%20Summary

### CODE REVIEW

**Comment by divegeek** [comment]
Note the commit I added to clarify the meaning of the boolean arguments.

Thanks!

**Comment by devinlundberg** [comment]
This actually doesn't fix the issue as demonstrated in the issue since it only modifies the java keyczart. You would need to change the python one as well (and probably c++).

**Comment by divegeek** [comment]
Good point. I reopened the issue.

**Comment by GoogleCodeExporter** [comment]
```
This is done.
```

Original comment by `stevew...@gmail.com` on 21 Jul 2008 at 10:01
- Changed state: **Fixed**

**Pull request merged**
