### PR TITLE
Adds keyczar 0.71f to maven repository.

### PR DESCRIPTION
**Pull request by phxql**
Hi,

this commit adds a compiled Keyczar 0.71f to the maven repository found in java/maven.

### CODE REVIEW

**Comment by wsargent** [comment]
+1

**Comment by wsargent** [comment]
It would be nice to have something GPG signed and with sha2sum files along side it as well...

**Comment by phxql** [comment]
Unfortunately I don't have the GPG key of the Keyczar team :)

**Comment by devinlundberg** [comment]
@divegeek Does google have a GPG key to sign binaries?

**Comment by wsargent** [comment]
Also, how do I know the binaries don't contain a special backdoor?  (from a paranoid security standpoint)

**Comment by phxql** [comment]
Good point. You don't.

I just thought it would be nice to have the newest version in the maven repository.

**Comment by oscaritoro** [comment]
Is version 0.66 really the latest one current available for maven?

**Comment by cosmin** [comment]
I'd like to see Keyczar synced to Maven Central rather than having to pull from a repository in Google code.

**Comment by divegeek** [comment]
cosmin, what would be involved in syncing with Maven. I'm not familiar with how it works.

**Comment by cosmin** [comment]
Sonatype has a guide for how to sync with central. Basically there are a few requirements. The Pom file needs to contain repository URL and the license info. Sources and java doc needs to be added too if they are not so it can all be published together. Lastly, releases need to be GPG signed (and there is a maven plugin for that too).

http://central.sonatype.org/pages/ossrh-guide.html

Here is a pull request I created for docopt for maven central sync that illustrates all of these points (although it was never merged and the only version in central is mine).

https://github.com/docopt/docopt.java/pull/6/files

I would be happy to contribute a pull request if there is interest.

**Comment by divegeek** [comment]
Yes, a pull request would be very welcome.

**Pull request merged**
