### PR TITLE
Correct/add copyright statements

### PR DESCRIPTION
**Pull request by divegeek**

### CODE REVIEW

**Comment by devinlundberg** [comment]
All the java stuff makes sense and is consistent with the top level license.

Everything inside of cpp/src/testing/gtest/ looks like it was another repo copied in as a static version of gtest. Was this file copied incorrectly?

**Comment by frumioj** [comment]
Agree with @devinlundberg - looks like the cc files have a different license still (not Apache).

**Comment by divegeek** [comment]
On the cc file, I used the statement from the surrounding code, which is BSD licensed.

**Comment by frumioj** [comment]
cpp/src/tools/swtoolkit/bin/runtest.py appears uncorrected FWIW...

**Comment by divegeek** [comment]
That shouldn't be an issue, since it's a test script that you won't be
distributing.

**Pull request merged**
