### PR TITLE
Replace the Memoize decorator with property cache to avoid memory leak.

### PR DESCRIPTION
**Pull request by tangyan**
The existing util.Memoize has memory leaks.  The cache is shared across session objects.

### CODE REVIEW

**Comment by tangyan** [comment]
I signed it!

**Comment by devinlundberg** [comment]
Looks good to me. @divegeek can you verify the CLA and merge?

**Comment by tangyan** [comment]
He is on vacation.  Any other owner can merge?

**Comment by divegeek** [comment]
I merged it. Thanks for the pull req!

**Comment by tangyan** [comment]
Thanks!

Can you bump up the version and make a new release?  Otherwise, it's hard
to us to pip install/update dependencies.

Thank you very much.

**Comment by divegeek** [comment]
I'll see if I can do that this weekend.

**Comment by divegeek** [comment]
I didn't have time over the weekend; I'll try to fit it in ASAP. Timing is
kind of bad for me; it's crunch time on my main job.

**Comment by tangyan** [comment]
We internally applied a temp hack solution to this memory leak and we are
OK for now.

I'd highly recommend to find a second owner who can do release for this
project, ;).

**Pull request merged**
